### ISSUE TITLE
Why is html bloat worse than css bloat?

### ISSUE THREAD

**Issue by mrmrs** [adamsilver/maintainablecss.com-jekyll#31]
You make the claim that reusing atomic styles will lead to "html bloat"
Do you have any data that it is harder to maintain and degrades performance? 
It seems that the payload of css is a larger hit to performance from my user testing. HTML bloat has seemed to be minimal, general less than 1kb of difference in an html file. While css bloat can lead to file sizes that even after minification and gzipping are more than 100kb larger than necessary due to the duplication in css.

Consider this excerpt from [Nicolas Gallaghers post](http://nicolasgallagher.com/about-html-semantics-front-end-architecture/)

> A note on raw file size and HTTP compression
> 
> Related to any discussion about modular/scalable CSS is a concern about file size and “bloat”. Nicole Sullivan’s talks often mention the file size savings (as well as maintenance improvements) that companies like Facebook experienced when adopting this kind of approach. Further to that, I thought I’d share my anecdotes about the effects of HTTP compression on pre-processor output and the extensive use of HTML classes.
> 
> When Twitter Bootstrap first came out, I rewrote the compiled CSS to better reflect how I would author it by hand and to compare the file sizes. After minifying both files, the hand-crafted CSS was about 10% smaller than the pre-processor output. But when both files were also gzipped, the pre-processor output was about 5% smaller than the hand-crafted CSS.
> 
> This highlights how important it is to compare the size of files after HTTP compression, because minified file sizes do not tell the whole story. It suggests that experienced CSS developers using pre-processors don’t need to be overly concerned about a certain degree of repetition in the compiled CSS because it can lend itself well to smaller file sizes after HTTP compression. The benefits of more maintainable “CSS” code via pre-processors should trump concerns about the aesthetics or size of the raw and minified output CSS.
> 
> In another experiment, I removed every class attribute from a 60KB HTML file pulled from a live site (already made up of many reusable components). Doing this reduced the file size to 25KB. When the original and stripped files were gzipped, their sizes were 7.6KB and 6KB respectively – a difference of 1.6KB. The actual file size consequences of liberal class use are rarely going to be worth stressing over.

Do you have any performance data about file size to counter these stats?

**Comment by adamsilver** [comment]
@mrmrs

> Why is html bloat worse than css bloat?

If I have a lot of CSS (or JS) in the the CSS (or JS) then that's okay, coz that's where it belongs.

Splitting concerns is a maintainability thing in itself, which I am sure you have read.

It tends to make more sense that CSS resides in CSS, and JS resides in JS, generally speaking anyway.

Also if websites utilise personalisation, then having smaller documents are beneficial because they can not be edge cached, that is the web/app server must be hit. Where as a CSS file is an offline, pre-built asset that _can_ benefit from caching.

With all this said, the performance bit, both ways is **very minor**. Something which I tried to make clear in the guides.

With regards to data, nope - I also tried to make this clear in the guides under "What about performance"?"

HTH
