### ISSUE TITLE
Discuss what didn't work for me

### ISSUE THREAD

**Issue by adamsilver** [adamsilver/maintainablecss.com-jekyll#5]
.moduleName {}
.moduleName .componentName {}

This is super clean and reusable, however, there is nothing to stop a different moduleName matching a different componentName, and when that happens you will inherit styles you didn't wish to happen. So you end up changing the name or overriding. Both not useful. Quite rare, but not helpful.

Second slightly lesser reason is, when you're inspecting .componentName you cannot tell there and then if you're dealing with a component OR a module. Would be nice to know without referring to CSS. HTML is modular too etc.

**Comment by rickerd** [comment]
Personally i don't know what a class .moduleName looks like.
But if i use .col-md-6 .moduleName .green
I know that i have a 50% width div that can have a certain "base-color" and i can override it with a green color.
SASS and LESS have such a great support for that to nest your class inside the other class so the .green class only applies for that certain "parent" class.

Of course you can use .moduleNameGreen. But it says more about the module rather than over the color it overriding.

Why is that not good? Because i have more flexibility about these classes.

I don't agree to use semantic naming, but that obvious it think.

**Comment by adamsilver** [comment]
Maintainablecss.com should provide you with all the answers as to why `.col-md-6` and `.green` are problematic but you seem convinced already so will leave it at that for now :)

**Comment by rickerd** [comment]
I've read it, that's why i'm commenting because i don't agree with your reasons why it should not be used.

I always have to check css code for know what .moduleName and .componentName means.

But on your answer shows already how not to handle people who doesn't work on the same line of you.

Sad

**Comment by adamsilver** [comment]
You stated that you "disagree" - that's fine you're allowed to disagree as have many others :)

You asked "Why is that not good?" - and I explained all of the "why"s in the website which I first pointed you to, and which you just stated that you have read already and I don't have any additional reasoning to hand at present for you to consume.

You stated "how not to handle people who doesn't work on the same line of you" - I am not sure why or what you're getting at - would you like me to make amends to MaintainableCSS?

**Comment by rickerd** [comment]
I would say that MaintainableCSS is old fashioned and has some good things in it for modularity and stuff.
But how to NOT reuse css and NOT use pre-processors, that's just a no-no for me.
A good modern developer has great CLI skills and can write JavaScript like an angel.
The only CSS and HTML frontend developer are in my opinion.. hobbyists

I'll leave it for now. I can go on and on and on, but it has not use for the both of us.

**Comment by ajaykarwal** [comment]
Just to jump in here and give me reasoning why MaintainableCSS is a good way of working.

Suppose you are using Bootstrap 3 and are trying to create a 'card' layout like this http://getbootstrap.com/components/#thumbnails-custom-content
You would use the following code

```
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="..." alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>
```

But then you decide to upgrade to Bootstrap 4 and all of a sudden the 'card' layout you had before is broken because the 'thumbnail' class has been dropped and you now have to refactor all your markup to look like this (which if you think about it, follows the principles of what MaintainableCSS is saying)

```
<div class="card">
  <img class="card-img-top" data-src="..." alt="Card image cap">
  <div class="card-block">
    <h4 class="card-title">Card title</h4>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Button</a>
  </div>
</div>
```

Had you used a semantic class in the first place and styled it to match, this problem would never occur.

@rickerd - MaintainableCSS is more tailored for developers who are not relying on a CSS framework to do half of the work for them. If it's not for you, that's cool.

**Comment by rickerd** [comment]
If you have Bootstrap3 and you make a card thing you just know it not compatible with a mayor version upgrade.

I would never like to write the whole css grid and stuff myself again.
It's like i reinvent the steam engine.

**Comment by ajaykarwal** [comment]
You should check out [Susy](http://susy.oddbird.net/l) which has all the power of responsive grids without the extra HTML classes.
